services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: api
    image: imageflow-api
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - /app/.venv
      - uploads_data:/app/uploads
      - outputs_data:/app/outputs
    env_file:
      - ./backend/.env
    depends_on:
      - db
      - redis
  celery_worker:
    command: celery -A celery_app worker --loglevel=info
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: worker
    image: imageflow-worker
    volumes:
      - ./backend:/app
      - /app/.venv
      - uploads_data:/app/uploads
      - outputs_data:/app/outputs
    env_file:
      - ./backend/.env
    depends_on:
      - db
      - redis
  db:
    image: postgres:18
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"
  redis:
    image: redis:8
    ports:
      - "6379:6379"
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - api
volumes:
  uploads_data:
  outputs_data: