server {
    listen 80;
    server_name localhost;

    autoindex off;
    client_max_body_size 10M;

    location /outputs/ {
        alias /app/outputs/;
        expires 30d;
        add_header Cache-Control "public, max-age=2592000, must-revalidate";
    }
}